package constant

const (
	PUSH_MESSAGE        = "PUSH_MESSAGE"
	TG_BOT_SEND_MESSAGE = "TG_BOT_SEND_MESSAGE"
	SEND_TICKET_MESSAGE = "SEND_TICKET_MESSAGE"
	SEND_EMAIL          = "SEND_EMAIL"
	SUBMIT_ORDER        = "SUBMIT_ORDER"
	NODE_BACKEND_TASK   = "NODE_BACKEND_TASK"
)
