package constant

const (
	PUSH_MESSAGE        = "PUSH_MESSAGE"
	TG_BOT_SEND_MESSAGE = "TG_BOT_SEND_MESSAGE"
	SEND_TICKET_MESSAGE = "SEND_TICKET_MESSAGE"
	EMAIL_CODE          = "EMAIL_CODE"
	SUBMIT_ORDER        = "SUBMIT_ORDER"
)
